version: '3.8'
services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=database
            - MYSQL_USER=username
        ports:
            - 3306:3306
        security_opt:
            - seccomp:unconfined
    adminer:
        image: adminer
        restart: always
        ports:
            - 8071:8080
    web:
        build: .
        ports:
            - 8070:80
        volumes:
            - ./:/var/www